# Generated by Django 4.2.30 on 2026-06-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_add_point_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointsubmission',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
